{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [test]","resource.type":"index_or_alias","resource.id":"test","index_uuid":"_na_","index":"test"}],"type":"index_not_found_exception","reason":"no such index [test]","resource.type":"index_or_alias","resource.id":"test","index_uuid":"_na_","index":"test"},"status":404}